### ISSUE TITLE
Idea for Animate.css implementation

### ISSUE THREAD

**Issue by HybridSolutions** [julianlloyd/scrollReveal.js#120]
Hi,

first of all, I'm a huge fan of your approach for this kind of plugin. Using keywords to build an effect, makes this a breeze to use :)

I'm sure you know Waypoint, and there's a feature that you might not agree with, but would make this plugin a real killer. An option to use animate (http://daneden.github.io/animate.css/) instead of the core effects would be awesome. It could for instance allow to use data-sr=" wait 1s, then animate fadeInUp". The "animate" keyword would tell the plugin to use animate.css and the following keyword would be the class name to add to the element along with the animated class name.

So, this,
```html
<div data-sr="wait 1s, then animate fadeInUp">...</div>
```

would become this
```html
<div class="animated fadeInUp">...</div>
```

I don't know if it would be possible to mix animate with your current keywords like wait or over but I don't see why not since I have used my own delay class when using animate to delay the animation.

What do you think about this?

PS: meanwhile I found this that does exactly what I suggested, but requires other script.
http://anijs.github.io/examples/scrollreveal/

Regards,
Hugo

**Comment by julianlloyd** [comment]
Adding support for animate.css has been requested a number of times, and your contribution in that effort is awesome. Thanks for the kind words, and the inspiration @HybridSolutions 

. . .

The `reset` keyword, or rather, the ability to have animations replay, is an important feature that I want to maintain support for. One of the key challenges I see is that animate.css is a collection of CSS keyframe animations, which unlike the CSS transitions that ScrollReveal generates, are not easily made bi-directional.

The most promising idea I’ve had is to actually read the animate.css file, and extract the animation keyframe data (as a string) so that it could be re-built dynamically—and with a counterpart reverse animation for `reset` support. In theory, this would allow the animate.css animations to not only be triggered by ScrollReveal, but also to customize them, and replay them with the `reset` keyword.

I’m still working things out, but this would be a significant refactor and be the next big release.

**Comment by HybridSolutions** [comment]
Hope you can pull this off! If you need testing, count me in :)
