### ISSUE TITLE
Uncaught TypeError: Cannot set property 'elems' of undefined

### ISSUE THREAD

**Issue by bradjerkson** [julianlloyd/scrollReveal.js#130]
Hi there, I installed this via bower. 
I am currently facing this error.

![Imgur](http://i.imgur.com/M63rLST.png?1)

**Comment by julianlloyd** [comment]
Hey @bradjerkson 

Reminds me of #91 with a similar error, due to *instantiating scrollReveal more than once.*

I’m not positive that is what’s happening here, but for starters, could you confirm you’re using scrollReveal.js `v2.1.0` and show more code details? (Better yet, provide a [jsfiddle](http://jsfiddle.com) to help troubleshoot.)
