### ISSUE TITLE
Using Classes for animations

### ISSUE THREAD

**Issue by MentalGear** [julianlloyd/scrollReveal.js#143]
Hi there,
Your plugin looks kinda cool, but what keeps me from using it is that it doens't seem to allow the usage of css classes for animations.
I think using css classes for your plugin would make code structuring much cleaner and also adhear to the separation principle of style and structure of HTML / CSS.

**Comment by julianlloyd** [comment]
Hey @MentalGear 

Thanks for the input, and you’re absolutely right—the current nature of scrollReveal is that it lives in your markup, which does not follow the established best practice of separation of markup and presentation.

So why is ScrollReveal the way it is?

Well, using classes typically requires a pre-defined list of animations… not only has this been brought up a few times already (issues #10 #114 and #97), but this already exists! Check out [WOW.js](https://github.com/matthieua/WOW) and [Animate.css](https://github.com/daneden/animate.css)

The power of ScrollReveal is easy creation _and_ management of **user defined animations.** What's more, ScrollReveal also allows for bi-directional animations… meaning whatever animations *you* create, ScrollReveal can reverse as elements leave the viewport (ie. the `reset` option/keyword.)

In regards to separation of markup, issues #1 and #122 address a serious need for a JavaScript API—so that this:
```html
<div data-sr="enter bottom, move 5px over 1.5s"> Foo </div>
<div data-sr="roll -30deg, enter bottom, move 15px"> Bar </div>
<div data-sr="roll -30deg, enter bottom, move 15px"> Bun </div>
```
Could be replaced with something like:

##### HTML
```html
<div id="sr-fade"> Foo </div>
<div class="sr-spin"> Bar </div>
<div class="sr-spin"> Bun </div>
```

##### JavaScript
```javascript
var sr = new scrollReveal();

sr('#sr-fade').define('enter bottom, move 5px over 1.5s');
sr('.sr-roll').define('roll -30deg, enter bottom, move 15px');
```
This is something I have in mind for `v3` of scrollReveal.js :wink:

**Comment by jayalfredprufrock** [comment]
How about new keywords "classadd" and "classremove" that take a single parameter, namely the class to be added or removed. This could be useful in other scenarios as well. For instance, after rolling an object into place you might want to trigger a fancier animation without having to use the javascript callback.
