### ISSUE TITLE
Best way to have all animations happen at load, even if they're not in the viewport?

### ISSUE THREAD

**Issue by benknight** [julianlloyd/scrollReveal.js#145]
I'd like to have all `data-sr` elements to do their sexy loading thing as if they're all in the viewport.

I think the best way to do this might be setting the viewport config to `document.body` since this will trick the library into thinking everything is visible.

**Comment by julianlloyd** [comment]
Hey @benknight 

This has actually come up before (I believe on Twitter). I believe the simplest way is to update the `isElemInViewport` method to always return true.

Here’s the original:
```Javascript
isElemInViewport: function( elem ){

  var elHeight = elem.domEl.offsetHeight;
  var elTop    = self.getOffset( elem.domEl ).top;
  var elBottom = elTop + elHeight;
  var vFactor  = elem.config.vFactor || 0;

  return ( confirmBounds() || isPositionFixed() );

  function confirmBounds(){

    var top        = elTop + elHeight * vFactor;
    var bottom     = elBottom - elHeight * vFactor;
    var viewBottom = self.scrolled + self.getViewportH();
    var viewTop    = self.scrolled;

    return ( top < viewBottom ) && ( bottom > viewTop );
  }

  function isPositionFixed(){

    var el    = elem.domEl;
    var style = el.currentStyle || window.getComputedStyle( el, null );

    return style.position === 'fixed';
  }
},
```
Which you could reduce to just:
```javascript
isElemInViewport: function(){
  return true;
},
```

**Comment by benknight** [comment]
Yeah that's pretty straightforward, I like it.

Even better, I think a developer could just override the `isElemInViewport` and avoid touching library code by doing this:

```javascript
scrollReveal.prototype.isElemInViewport = function () { return true; }
```

Still I slightly lean towards setting the viewport config to `document.body` since it's not overriding the module's API which could change in future versions.

Thanks!

**Comment by julianlloyd** [comment]
:beers:

**Comment by Glidias** [comment]
Could there be a convention that if viewFactor is "zero", no view factor is considered and thus the function always returns true? If they wish to perform viewFactor on the edge though, then they'd have to resort to a minuscule epsilon value like "0.000001" though,   hmmmm..not that elegant. Also, magic numbers (even if it's magic zero) to imply a different functionality might be an anti-pattern. On flipside, zero does arguably make logical sense if you describe it as "so long as >=0% of it is visible", which should return true in every circumstance, right? Because there can never be a logical negative <% exposure, if  you're referring to magnitude of exposure only. However, the actual code implementation treats `viewFactor` as a vector quantity (with a directional implications when using negative vs positive values) and not as a mere magnitude check.
